### ISSUE TITLE
Reboot from initramfs doesn't work, next boot hangs

### ISSUE THREAD

**Issue by jjakob** [neilbrown/gnubee-tools#18]
Image gbpc2-5.4:
- Boot into the initramfs
- install to disk with config
- try to reboot with `reboot` or `poweroff`: no response
- init 0: drops back into initramfs shell
- a power cycle is required to reboot

**Comment by neilbrown** [comment]
When config finished it prints a message suggesting that you use "reboot -f".  This works.

**Comment by jjakob** [comment]
It does. Thanks.
