### ISSUE TITLE
/etc/network/ is a world-writable directory

### ISSUE THREAD

**Issue by fmarier** [neilbrown/gnubee-tools#23]
I used the [tiger](https://savannah.nongnu.org/projects/tiger/) security checker on my GnuBee and it picked up the fact that `/etc/network/` is world-writable:
```
# Checking for writable directories...
--FAIL-- [fsys008f] The following directories are world writable:
/etc/network/
/etc/network/

# Performing check of embedded pathnames...
--WARN-- [embed003w] Path `/etc/network/if-up.d/mountnfs' contains `/etc/network' which is world writable.
         Embedded references in: /etc/init.d/mountnfs.sh
```

Since this is rewritten on boot by the initramfs, I ended up putting the following in `/etc/rc.local`:

    chmod 755 /etc/network

but I imagine there's a way to fix the problem at the source.

**Comment by neilbrown** [comment]
This is now fixed.  Thanks for the report.
