### ISSUE TITLE
missing rsync dependency

### ISSUE THREAD

**Issue by reukiodo** [neilbrown/gnubee-tools#37]
```
  INSTALL /home/gnubee/gnubee-tools/build/include
/bin/sh: 1: rsync: not found
make[1]: *** [/home/gnubee/linux-gnubee-v6.1/Makefile:1357: headers_install] Error 127
make[1]: Leaving directory '/home/gnubee/linux-gnubee-v6.1/O'
make: *** [Makefile:231: __sub-make] Error 2
```
`rsync` package should be included in README.md dependency install list

`apt -y install install git make gcc flex bison busybox bc libssl-dev u-boot-tools unzip mdadm dropbear cryptsetup-bin mtd-utils u-boot-tools xfsprogs btrfs-progs lvm2 evtest debootstrap rsync`

**Comment by neilbrown** [comment]
Thanks for the report.  Fixed now.
